export default {
  default: {
    url: "/public/question-mark.gltf",
    offset: -1,
    startingRotation: 3.3,
    title: "?",
    description: "...",
    date: "29/12/2023",
  },
  info: {
    url: "/public/info-board.gltf",
    scale: 1.5,
    startingRotation: -0.6,
    title: "A Month of Models",
    description:
      "A creative adventure into the use of PicoCAD. Taking time each day in January of 2024 to create and texture a model.",
    date: "30/12/2023",
  },
  1: {
    url: "/public/crate.gltf",
    offset: -1,
    scale: 2,
    title: "Crate",
    description: "A wooden crate with a label.",
    date: "30/12/2023",
  },
  2: {
    url: "/public/barrel.gltf",
    title: "Barrel",
    description: "A barrel, painted an enticing red.",
    date: "02/01/2024",
    scale: 1.5,
  },
  3: {
    url: "/public/pigeon.gltf",
    title: "Pigeon",
    description: "A typcial city Pigeon.",
    date: "03/01/2024",
    scale: 1.2,
  },
  4: {
    url: "/public/radio.gltf",
    title: "Radio",
    description: "An old wooden radio.",
    date: "04/01/2024",
    scale: 2,
  },
  5: {
    url: "/public/hotdog.gltf",
    title: "Hotdog",
    description: "A plain hotdog.",
    date: "05/01/2024",
    scale: 0.75,
  },
  6: {
    url: "/public/loaf.gltf",
    title: "loaf",
    description: "A pigeon's worst best friend.",
    date: "06/01/2024",
    scale: 0.75,
  },
  7: {
    url: "/public/tardis.gltf",
    title: "TARDIS",
    description: "A blue police box.",
    date: "07/01/2024",
    scale: 0.8,
  },
  8: {
    url: "/public/half-loaf.gltf",
    title: "loaf",
    description: "Half a pigeon's worst best friend.",
    date: "08/01/2024",
  },
};
